WIP

diff --git a/.github/workflows/draw_keymaps.yaml b/.github/workflows/draw_keymaps.yaml
--- a/.github/workflows/draw_keymaps.yaml
+++ b/.github/workflows/draw_keymaps.yaml
@@ -97,44 +97,24 @@ jobs:
 
       - name: Install keymap-drawer (pypi)
         if: inputs.install_branch == ''
-        run: python3 -m pip install keymap-drawer
+        run: |
+          [ -n "${{ inputs.install_version }}" ] && version="==${{ inputs.install_version }}" || version=""
+          pipx install "keymap-drawer$version"
 
       - name: Install keymap-drawer (git)
         if: inputs.install_branch != ''
-        run: python3 -m pip install "git+${{ inputs.install_repo }}@${{ inputs.install_branch }}"
+        run: pipx install "git+${{ inputs.install_repo }}@${{ inputs.install_branch }}"
 
       - name: Install west
         if: inputs.west_config_path != ''
-        run: python3 -m pip install west
+        run: pipx install west
 
-      - name: Cache west modules
-        if: inputs.west_config_path != ''
-        uses: actions/cache@v4
-        continue-on-error: true
-        env:
-          cache_name: cache-zephyr-3.5.0-modules
-        with:
-          path: |
-            modules/
-            tools/
-            zephyr/
-            bootloader/
-            zmk/
-          key: ${{ runner.os }}-build-${{ env.cache_name }}-${{ hashFiles('**/west.yml', '**/build.yaml') }}
-          restore-keys: |
-            ${{ runner.os }}-build-${{ env.cache_name }}-
-            ${{ runner.os }}-build-
-            ${{ runner.os }}-
-
-      - name: West Init
+      - name: Fetch west modules
         if: inputs.west_config_path != ''
         run: |
-          ls -Rhl $GITHUB_WORKSPACE
           west init -l ${{ inputs.west_config_path }}
-
-      - name: West Update
-        if: inputs.west_config_path != ''
-        run: west update
+          west config --local manifest.project-filter " -zmk,-zephyr"
+          west update --fetch-opt=--filter=tree:0
 
       - name: Draw keymaps
         id: draw
@@ -185,82 +165,100 @@ jobs:
               "&code_blk": "```",
               "&home_dir": "~/"
             }
+        continue-on-error: ${{ !inputs.fail_on_error }}
         run: |
+          [ "${{ inputs.debug_mode }}" == "true" ] && set -x
+
           get_args() {
               local keyboard=$2
+              local output=()
+
               eval set -- "$1"
               for arg; do
                   local key=${arg%%:*}
                   local val=${arg#*:}
                   if [ "$key" = "$keyboard" ]; then
-                      echo "$val"
+                      output+=("$val")
                       break
                   fi
               done
+              echo "${output[@]}"
           }
 
-          declare -a DRAWINGS
+          check_for_layout_args() {
+              local args=("$@")
+
+              for val in "-j" "--qmk-info-json" "-k" "--qmk-keyboard" "-z" "--zmk-keyboard" "-d" "--dts-layout" "--ortho-layout" "-n" "--cols-thumbs-notation"; do
+                  for item in "${args[@]}"; do
+                      if [ "$val" = "$item" ]; then return 0; fi
+                  done
+              done
+
+              return 1
+          }
+
+          shopt -s nullglob extglob
+
+          artifacts=()
           error_occurred=0
           mkdir -p "${{ inputs.output_folder }}"
-          mkdir -p "${{ inputs.output_folder }}/base"
 
           config_path="${{ inputs.config_path }}"
           [ -e "$config_path" ] && config_arg=(-c "$config_path") || config_arg=()
-          echo "INFO: using config args: ${config_arg[@]}"
+          echo "INFO: using config args:" "${config_arg[@]}"
+
+          [ "${{ inputs.debug_mode }}" == "true" ] && debug_arg="-d" || debug_arg=""
+
           for keymap_file in ${{ inputs.keymap_patterns }}; do
               keyboard=$(basename -s .keymap "$keymap_file")
               echo "INFO: drawing for $keyboard"
 
-              parse_args=$(get_args "${{ inputs.parse_args }}" "$keyboard")
-              echo "INFO:   got extra parse args: $parse_args"
-              draw_args=$(get_args "${{ inputs.draw_args }}" "$keyboard")
-              echo "INFO:   got extra draw args: $draw_args"
+              IFS=" " read -r -a parse_args        <<< "$(get_args "${{ inputs.parse_args }}" "$keyboard")"
+              echo "INFO:   got extra parse args:"       "${parse_args[@]}"
+              IFS=" " read -r -a draw_args         <<< "$(get_args "${{ inputs.draw_args }}" "$keyboard")"
+              echo "INFO:   got extra draw args:"        "${draw_args[@]}"
+              IFS=" " read -r -a extra_keymap_yaml <<< "$(get_args "${{ inputs.extra_keymap_yaml }}" "$keyboard")"
+              echo "INFO:   got extra keymap YAML args:" "${extra_keymap_yaml[@]}"
 
               json_path="${{ inputs.json_path }}"
-              if [ -f "$json_path/${keyboard}.json" ]; then
+              if check_for_layout_args "${draw_args[@]}"; then
+                  echo "INFO:   found layout specifiers in draw args"
+              elif [ -n "$json_path" ] && [ -f "$json_path/${keyboard}.json" ]; then
                   echo "INFO:   found $json_path/${keyboard}.json";
-                  draw_args+=" -j $json_path/${keyboard}.json"
+                  draw_args+=(-j "$json_path/${keyboard}.json")
+              else
+                  dts_candidates=({,config/}boards/*/*/${keyboard}-layout{,s}.dtsi)
+                  if [ ${#dts_candidates[@]} -gt 0 ]; then
+                      echo "INFO:   found ${dts_candidates[0]}";
+                      draw_args+=(-d "${dts_candidates[0]}")
+                  fi
               fi
 
-              # Full (regular) render
-              echo "Generating YAML:"
-              keymap "${config_arg[@]}" parse -z "$keymap_file" $parse_args
+              tmp_yaml=$(mktemp)
+              tmp_svg=$(mktemp)
 
-              keymap "${config_arg[@]}" parse -z "$keymap_file" $parse_args \
-                > "${{ inputs.output_folder }}/$keyboard.yaml" \
-              && \
-              keymap "${config_arg[@]}" draw "${{ inputs.output_folder }}/$keyboard.yaml" $draw_args \
-                > "${{ inputs.output_folder }}/$keyboard.svg"
+              if keymap $debug_arg "${config_arg[@]}" parse -z "$keymap_file" "${parse_args[@]}" >"$tmp_yaml"; then
+                  mv "$tmp_yaml" "${{ inputs.output_folder }}/$keyboard.yaml"
+                  artifacts+=("${{ inputs.output_folder }}/$keyboard.yaml")
+              else
+                  echo "ERROR: parsing failed for $keyboard!"
+                  error_occurred=1
+                  continue
+              fi
 
-              draw_status=$?
-              if [ $draw_status -ne 0 ]; then
-                  echo "::error::keymap draw failed (exit $draw_status)"
+              if keymap $debug_arg "${config_arg[@]}" draw "${{ inputs.output_folder }}/$keyboard.yaml" "${extra_keymap_yaml[@]}" "${draw_args[@]}" >"$tmp_svg"; then
+                  mv "$tmp_svg" "${{ inputs.output_folder }}/$keyboard.svg"
+                  artifacts+=("${{ inputs.output_folder }}/$keyboard.svg")
+              else
+                  echo "ERROR: drawing failed for $keyboard!"
                   error_occurred=1
               fi
-
-              # BASE-only render
-              keymap "${config_arg[@]}" draw "${{ inputs.output_folder }}/$keyboard.yaml" \
-                -s BASE --keys-only $([[ -n "$json_path/${keyboard}.json" ]] && echo "-j $json_path/${keyboard}.json") \
-                > "${{ inputs.output_folder }}/base/$keyboard.svg"
-
-              ls -hal "${{ inputs.output_folder }}"
-              ls -hal "${{ inputs.output_folder }}/base"
-
-              base_status=$?
-              if [ $base_status -ne 0 ]; then
-                  echo "::error::base-only keymap draw failed (exit $base_status)"
-                  error_occurred=1
-              fi
-
-              DRAWINGS+=(\"${{ inputs.output_folder }}/$keyboard.yaml\" \
-                       \"${{ inputs.output_folder }}/$keyboard.svg\" \
-                       \"${{ inputs.output_folder }}/base/$keyboard.svg\")
           done
-          IFS=','
-          echo "DRAWINGS=[${DRAWINGS[*]}]" >> $GITHUB_OUTPUT
-          unset IFS
 
-          if [ "${{ inputs.fail_on_error }}" == "true" ] && [ $error_occurred -eq 1 ]; then
+          joined_artifacts=$(printf '"%s", ' "${artifacts[@]}")
+          printf 'artifacts=[%s]\n' "${joined_artifacts%, }" >> "$GITHUB_OUTPUT"
+
+          if [ $error_occurred -eq 1 ]; then
               exit 1
           fi
 
@@ -270,28 +268,17 @@ jobs:
         run: |
           echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
 
-      - name: Debug Git Status
-        run: |
-          git status
-          git diff --stat
-
       - name: Commit updated images
         if: ( inputs.destination == 'commit' || inputs.destination == 'both' )
         uses: stefanzweifel/git-auto-commit-action@v5
         with:
-          file_pattern: |
-            keymap-drawer/**/*.svg
-            keymap-drawer/**/*.yaml
-          disable_globbing: false
-          add_options: '-u'
-
-
+          file_pattern: '${{ inputs.output_folder }}/*.svg ${{ inputs.output_folder }}/*.yaml'
           # So the previous commit is amended instead of creating a new one when desired
           # See:
           # - https://github.com/stefanzweifel/git-auto-commit-action#using---amend-and---no-edit-as-commit-options
           # - https://github.com/stefanzweifel/git-auto-commit-action/issues/159#issuecomment-845347950
           # - https://github.com/actions/checkout
-          commit_message: "${{ (inputs.amend_commit == true && steps.last_commit_message.outputs.msg) || inputs.commit_message }}"
+          commit_message: '${{ (inputs.amend_commit == true && steps.last_commit_message.outputs.msg) || inputs.commit_message }}'
           commit_options: "${{ (inputs.amend_commit == true && '--amend --no-edit') || '' }}"
           push_options: "${{ (inputs.amend_commit == true && '--force-with-lease') || '' }}"
           skip_fetch: ${{ inputs.amend_commit == true }}
@@ -301,7 +288,15 @@ jobs:
         if: ( inputs.destination == 'artifact' || inputs.destination == 'both' )
         uses: actions/upload-artifact@v4
         with:
-          name: "${{ inputs.artifact_name }}"
+          name: '${{ inputs.artifact_name }}'
           path: |
-            ${{ join(fromJSON(steps.draw.outputs.DRAWINGS), '
+            ${{ join(fromJSON(steps.draw.outputs.artifacts), '
             ') }}
+
+      - name: Check job success
+        if: ${{ !inputs.fail_on_error }}
+        run: |
+          if [ "${{ steps.draw.outcome }}" == "failure" ]; then
+            echo "The draw step failed for some keymaps, please check the logs of that step above!"
+            exit 1
+          fi
