adjust configs to point to correct files & not overwrite qwerty.yaml

diff --git a/.github/workflows/draw_keymaps.yaml b/.github/workflows/draw_keymaps.yaml
--- a/.github/workflows/draw_keymaps.yaml
+++ b/.github/workflows/draw_keymaps.yaml
@@ -223,20 +223,32 @@ jobs:
               fi
 
               # Full (regular) render
-              keymap "${config_arg[@]}" parse -z "$keymap_file" $parse_args >"${{ inputs.output_folder }}/$keyboard.yaml" \
+              echo "Generating YAML:"
+              keymap "${config_arg[@]}" parse -z "$keymap_file" $parse_args
+
+              keymap "${config_arg[@]}" parse -z "$keymap_file" $parse_args \
+                > "${{ inputs.output_folder }}/$keyboard.yaml" \
               && \
-              keymap "${config_arg[@]}" draw "${{ inputs.output_folder }}/$keyboard.yaml" $draw_args >"${{ inputs.output_folder }}/$keyboard.svg" \
-              || \
-              {
-                  echo "ERROR: parsing or drawing failed for $keyboard!"
+              keymap "${config_arg[@]}" draw "${{ inputs.output_folder }}/$keyboard.yaml" $draw_args \
+                2>&1 > "${{ inputs.output_folder }}/$keyboard.svg"
+
+              draw_status=$?
+              if [ $draw_status -ne 0 ]; then
+                  echo "::error::keymap draw failed (exit $draw_status)"
                   error_occurred=1
-              }
+              fi
 
               # BASE-only render
               keymap "${config_arg[@]}" draw "${{ inputs.output_folder }}/$keyboard.yaml" \
                 -s BASE --keys-only $([[ -n "$json_path/${keyboard}.json" ]] && echo "-j $json_path/${keyboard}.json") \
-                > "${{ inputs.output_folder }}/base/$keyboard.svg" \
-              || error_occurred=1
+                2>&1 > "${{ inputs.output_folder }}/base/$keyboard.svg"
+
+              base_status=$?
+              if [ $base_status -ne 0 ]; then
+                  echo "::error::base-only keymap draw failed (exit $base_status)"
+                  error_occurred=1
+              fi
+
 
               DRAWINGS+=(\"${{ inputs.output_folder }}/$keyboard.yaml\" \
                        \"${{ inputs.output_folder }}/$keyboard.svg\" \
